# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  name: Default

variables:
  solution: './APITempoDio/APITempoDio.sln'
  buildPlataform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: useDotNet@2
  displayName: 'Install .Net SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore $(solution)
  displayName: 'Restore Solution'

- script: dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Build Solution'

- script: dotnet test $(solution) --configuration $(buildConfiguration) --collect:"XPlat Code Coverage"
  displayName: 'Run Unit Tests with Coverage'
  continueOnError: true # Important: Allow pipeline to continue even if tests fail

- task: Docker@2
  inputs:
    containerRegistry: 'acrapidemo2'
    repository: 'api-dio-repo-build-step'
    command: 'buildAndPush'
    Dockerfile: './APITempoDio/APITempoDio/Dockerfile'

